// Import all test modules
import './specs/constructor.spec'
import './specs/spell.spec'
import './specs/suggest.spec'
import './specs/analyze.spec'
import './specs/analyzeSync.spec'
import './specs/stem.spec'
import './specs/stemSync.spec'
import './specs/generate.spec'
import './specs/generateSync.spec'
import './specs/dictionary-mgmt.spec'
import './specs/getters.spec'